---
- name: Install metric beat
  hosts: elk
  remote_user: azureuser
  become: true
  tasks:

# Use command module
  - name: Download metricbeat
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

# Use command module
  - name: Install metricbeat
    command: sudo dpkg -i metricbeat-7.6.1-amd64.deb

# Use copy module
  - name: Drop in metricbeat config
    copy:
      src: /etc/ansible/files/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

# Use command module
  - name: Enable & configure docker module for metric beat
    command: sudo metricbeat modules enable docker

# Use command module
  - name: setup metric beat
    command: metricbeat setup

# Use command module
  - name: Start metric beat
    command: sudo service metricbeat start

# Use systemd module
  - name: Enable service metric beat on boot
    systemd:
      name: metricbeat
      enabled: yes